### ISSUE TITLE
Can't read out IP address

### ISSUE THREAD

**Issue by Frostlock** [bat-serjo/PyIface#5]
I can read out the interfaces but if I want to get the addr property I get an error message. Here is a minimal example in the python console:
```
>>> import pyiface
>>> pyiface.getIfaces()[0].addr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyiface/iface.py", line 291, in addr
    ifr = self.__newIfreqWithName()
  File "/usr/local/lib/python2.7/dist-packages/pyiface/iface.py", line 181, in __newIfreqWithName
    ifr.ifr_name = self._name
TypeError: expected c_ubyte_Array_16 instance, got str
```
 Any thoughts on what is going on? :)
Thanks!

**Comment by petri** [comment]
I can confirm this on Debian stable, Python 2.7.

**Comment by petri** [comment]
Easy fix. Just replace the:

     ifr.ifr_name = self._name

with:

    ifr.ifr_name = (c_ubyte*IFNAMSIZ) (*bytearray(self._name))

That's how it's done elsewhere in the same module, anyway. For what it's worth, it might actually be better to use:

    ifr.ifr_name = (c_ubyte*IFNAMSIZ).from_buffer_copy(self._name)

For reasoning, see http://stackoverflow.com/questions/21483482/efficient-way-to-convert-string-to-ctypes-c-ubyte-array-in-python, especially the chosen answer by eryksun.

**Comment by petri** [comment]
A PR submitted; @bat-serjo, think you can merge and make a release?
